-- performance-app: migrations 0007 to 0016 (Nutrition, phases 2a and 2b) in one file.
-- GENERATED by scripts/build-release-sql.mjs. Do not edit; edit the migrations instead.
-- Run once, whole, in the Supabase SQL Editor, on a database that already has 0001 to 0006.
-- Files: 0007_nutrition_base.sql, 0008_weekly_targets_pillar.sql, 0009_nutrition_diary.sql, 0010_nutrition_close.sql, 0011_nutrition_week.sql, 0012_nutrition_progress.sql, 0013_nutrition_cron.sql, 0014_food_measures.sql, 0015_nutrition_challenge.sql, 0016_nutrition_history.sql

-- ===== 0007_nutrition_base.sql =====
-- Phase 2a, base: nutrition profile columns, pillar periods and server-only event kinds.

-- Profile -------------------------------------------------------------------------------------

alter table public.profiles
  add column activity_level text check (activity_level in
    ('sedentary', 'light', 'moderate', 'active', 'very_active')),
  add column nutrition_pace text not null default 'standard'
    check (nutrition_pace in ('gentle', 'standard')),
  add column nutrition_enabled boolean not null default false,
  add column nutrition_days_per_week smallint not null default 5
    check (nutrition_days_per_week between 3 and 7);

-- Periods -------------------------------------------------------------------------------------
-- A day is only judged when it falls inside a period. A period with ended_on = started_on - 1
-- (turned on and off the same day) covers no day.

create table public.nutrition_periods (
  user_id    uuid not null references auth.users on delete cascade,
  started_on date not null,
  ended_on   date check (ended_on is null or ended_on >= started_on - 1),
  primary key (user_id, started_on)
);

alter table public.nutrition_periods enable row level security;
create policy nutrition_periods_select_own on public.nutrition_periods
  for select to authenticated using (user_id = auth.uid());
revoke insert, update, delete, truncate on public.nutrition_periods from anon, authenticated;
revoke select on public.nutrition_periods from anon;

create or replace function public.profiles_nutrition_period() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_today date := public.local_today(new.id);
begin
  if new.nutrition_enabled then
    if tg_op = 'UPDATE' and old.nutrition_enabled then return null; end if;
    -- Turned back on the day it was turned off: the same period continues.
    update public.nutrition_periods set ended_on = null
     where user_id = new.id and ended_on = v_today - 1;
    if not found then
      insert into public.nutrition_periods (user_id, started_on) values (new.id, v_today)
      on conflict (user_id, started_on) do update set ended_on = null;
    end if;
  else
    update public.nutrition_periods set ended_on = v_today - 1
     where user_id = new.id and ended_on is null;
  end if;
  return null;
end $$;

create trigger profiles_nutrition_period after insert or update of nutrition_enabled on public.profiles
  for each row execute function public.profiles_nutrition_period();

create or replace function public.nutrition_active_on(p_user uuid, p_day date) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.nutrition_periods
     where user_id = p_user and started_on <= p_day and (ended_on is null or ended_on >= p_day))
$$;

revoke all on function public.profiles_nutrition_period(), public.nutrition_active_on(uuid, date)
  from public, anon, authenticated;

-- Server-only event kinds ---------------------------------------------------------------------
-- Clients write as authenticated and go through RLS; security definer functions write as the
-- owner and do not. The insert policy keeps clients from writing a server_only kind.

alter table public.event_kinds add column server_only boolean not null default false;
insert into public.event_kinds (pillar, kind, server_only) values
  ('nutrition', 'day_logged', true),
  ('nutrition', 'day_on_target', true),
  ('nutrition', 'macros_balanced', true);

drop policy activity_events_insert_own on public.activity_events;
create policy activity_events_insert_own on public.activity_events for insert to authenticated
  with check (
    user_id = auth.uid()
    and not exists (
      select 1 from public.event_kinds k
       where k.pillar = activity_events.pillar and k.kind = activity_events.kind and k.server_only)
  );

-- A closing that runs late must not break: server-only kinds skip the 14-day window.
create or replace function public.validate_activity_event() returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tz          text;
  v_today       date;
  v_server_only boolean;
begin
  select k.server_only into v_server_only
    from public.event_kinds k where k.pillar = new.pillar and k.kind = new.kind;
  if not found then
    raise exception 'unknown_kind' using errcode = '22023';
  end if;
  if octet_length(new.payload::text) > 4096 then
    raise exception 'payload_too_large' using errcode = '22023';
  end if;
  if v_server_only then return new; end if;
  select timezone into v_tz from public.profiles where id = new.user_id;
  v_today := (now() at time zone coalesce(v_tz, 'America/Sao_Paulo'))::date;
  if new.occurred_on > v_today or new.occurred_on < v_today - 14 then
    raise exception 'out_of_window' using errcode = '22023';
  end if;
  return new;
end $$;

-- ===== 0008_weekly_targets_pillar.sql =====
-- Weekly targets per pillar (phase 2a, spec 5.5). weekly_targets gains a pillar and every reader
-- of the table changes with it. Bodies copied from 0002_gamification.sql; only the pillar lines differ.

alter table public.weekly_targets
  add column pillar public.pillar not null default 'strength';
alter table public.weekly_targets drop constraint weekly_targets_pkey;
alter table public.weekly_targets add primary key (user_id, pillar, week_start);

-- The signature changes, so the old function goes first (a default would leave two overloads).
drop function public.week_target_for(uuid, date);

create function public.week_target_for(p_user uuid, p_week date, p_pillar public.pillar default 'strength')
returns smallint
language plpgsql security definer set search_path = public as $$
declare
  v smallint;
begin
  select target into v from public.weekly_targets
   where user_id = p_user and pillar = p_pillar and week_start = p_week;
  if found then return v; end if;
  -- A week nothing touched while it ran: the value in force then is the one frozen for the next
  -- touched week after it or, failing that, the profile's.
  select target into v from public.weekly_targets
   where user_id = p_user and pillar = p_pillar and week_start > p_week order by week_start limit 1;
  if v is null then
    if p_pillar = 'nutrition' then
      select nutrition_days_per_week into v from public.profiles where id = p_user;
    else
      select days_per_week into v from public.profiles where id = p_user;
    end if;
  end if;
  insert into public.weekly_targets (user_id, pillar, week_start, target)
  values (p_user, p_pillar, p_week, coalesce(v, case when p_pillar = 'nutrition' then 5 else 3 end))
  on conflict do nothing;
  select target into v from public.weekly_targets
   where user_id = p_user and pillar = p_pillar and week_start = p_week;
  return v;
end $$;

-- Changing a pillar's days per week freezes the running week with the old value first.
create or replace function public.freeze_week_target() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if new.days_per_week is distinct from old.days_per_week then
    insert into public.weekly_targets (user_id, pillar, week_start, target)
    values (old.id, 'strength', public.local_week_start(old.id), old.days_per_week)
    on conflict do nothing;
  end if;
  if new.nutrition_days_per_week is distinct from old.nutrition_days_per_week then
    insert into public.weekly_targets (user_id, pillar, week_start, target)
    values (old.id, 'nutrition', public.local_week_start(old.id), old.nutrition_days_per_week)
    on conflict do nothing;
  end if;
  return new;
end $$;

drop trigger profiles_freeze_target on public.profiles;
create trigger profiles_freeze_target
  before update of days_per_week, nutrition_days_per_week on public.profiles
  for each row execute function public.freeze_week_target();

revoke all on function public.week_target_for(uuid, date, public.pillar) from public, anon, authenticated;

create or replace function public.award_xp() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_week   date := public.week_start_of(new.occurred_on);
  v_target smallint;
  v_count  integer;
begin
  -- One award at a time per user: the counts below decide the amount.
  perform pg_advisory_xact_lock(hashtextextended('xp:' || new.user_id::text, 0));
  if new.pillar <> 'strength' then return null; end if;

  if new.kind = 'workout_completed' then
    v_target := public.week_target_for(new.user_id, v_week, 'strength');
    select count(*) into v_count from public.xp_ledger
     where user_id = new.user_id and week_start = v_week and reason = 'workout';
    if v_count < v_target then
      insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
      values (new.user_id, 'strength', public.session_xp(v_target, v_count + 1), 'workout', new.id, v_week);
      if v_count + 1 = v_target then
        insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
        values (new.user_id, 'strength', 150, 'week_target', new.id, v_week);
        -- A goal met in a week already judged (a session logged into the past) changes that
        -- week's verdict: replay the streak from the start.
        if exists (select 1 from public.streaks
                    where user_id = new.user_id and kind = 'training_week' and last_period >= v_week) then
          perform public.close_weeks(new.user_id, true);
        end if;
      end if;
    else
      select count(*) into v_count from public.xp_ledger
       where user_id = new.user_id and week_start = v_week and reason = 'workout_extra';
      if v_count < 2 then
        insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
        values (new.user_id, 'strength', 25, 'workout_extra', new.id, v_week);
      end if;
    end if;
  elsif new.kind = 'pr' then
    select count(*) into v_count from public.xp_ledger
     where user_id = new.user_id and week_start = v_week and reason = 'pr';
    if v_count < 3 then
      insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
      values (new.user_id, 'strength', 30, 'pr', new.id, v_week);
    end if;
  elsif new.kind = 'weight_logged' then
    if not exists (
      select 1 from public.xp_ledger l join public.activity_events e on e.id = l.event_id
       where l.user_id = new.user_id and l.reason = 'weight' and e.occurred_on = new.occurred_on
    ) then
      insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
      values (new.user_id, 'strength', 10, 'weight', new.id, v_week);
    end if;
  end if;
  perform public.evaluate_achievements(new.user_id);
  return null;
end $$;

create or replace function public.progress_card(p_user uuid) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  v_week   date := public.local_week_start(p_user);
  v_total  bigint := public.total_xp(p_user);
  v_target smallint;
  v_streak public.streaks%rowtype;
  v_count  jsonb;
begin
  v_target := coalesce(
    (select target from public.weekly_targets where user_id = p_user and pillar = 'strength' and week_start = v_week),
    (select days_per_week from public.profiles where id = p_user), 3);
  select * into v_streak from public.streaks where user_id = p_user and kind = 'training_week';
  select jsonb_build_object(
           'workouts', count(*) filter (where reason = 'workout'),
           'extras', count(*) filter (where reason = 'workout_extra'),
           'prs', count(*) filter (where reason = 'pr'),
           'target_hit', count(*) filter (where reason = 'week_target') > 0)
    into v_count
    from public.xp_ledger where user_id = p_user and week_start = v_week;
  return jsonb_build_object(
    'total_xp', v_total,
    'level', public.level_json(v_total),
    'pillars', (
      select coalesce(jsonb_object_agg(p.name, public.level_json(p.xp) || jsonb_build_object('xp', p.xp)), '{}'::jsonb)
        from (select e::text as name,
                     coalesce((select sum(amount) from public.xp_ledger where user_id = p_user and pillar = e), 0)::bigint as xp
                from unnest(enum_range(null::public.pillar)) e) p
       where p.name = 'strength' or p.xp > 0),
    'week', jsonb_build_object('start', v_week, 'xp', public.week_xp(p_user, v_week), 'max', 960, 'target', v_target) || v_count,
    'streak', jsonb_build_object('current', coalesce(v_streak.current, 0), 'best', coalesce(v_streak.best, 0),
                                 'shields', coalesce(v_streak.shields, 0)),
    'achievements', coalesce((
      select jsonb_agg(jsonb_build_object('code', code, 'unlocked_at', unlocked_at) order by unlocked_at, code)
        from public.user_achievements where user_id = p_user), '[]'::jsonb)
  );
end $$;

create or replace function public.get_my_progress() returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_uid   uuid := auth.uid();
  v_today date;
  v_card  jsonb;
begin
  if v_uid is null then raise exception 'not_signed_in' using errcode = '28000'; end if;
  if not exists (select 1 from public.profiles where id = v_uid) then
    raise exception 'no_profile' using errcode = 'P0002';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('xp:' || v_uid::text, 0));
  v_today := public.local_today(v_uid);
  perform public.week_target_for(v_uid, public.week_start_of(v_today), 'strength');
  perform public.week_target_for(v_uid, public.week_start_of(v_today), 'nutrition');
  perform public.close_weeks(v_uid);
  perform public.evaluate_achievements(v_uid);
  v_card := public.progress_card(v_uid);
  return v_card || jsonb_build_object(
    'today', v_today,
    'stats', public.achievement_stats(v_uid) || jsonb_build_object('level', (v_card -> 'level' ->> 'level')::int),
    'week', (v_card -> 'week') || jsonb_build_object('weighed_today', exists (
      select 1 from public.xp_ledger l join public.activity_events e on e.id = l.event_id
       where l.user_id = v_uid and l.reason = 'weight' and e.occurred_on = v_today)));
end $$;

-- Daily safety net (0003 schedules it): freezes the new week's target, closes weeks and hands out
-- streak badges for people who did not open the app.
create or replace function public.close_all_weeks() returns integer
language plpgsql security definer set search_path = public as $$
declare
  r record;
  n integer := 0;
begin
  for r in select id from public.profiles loop
    perform public.week_target_for(r.id, public.local_week_start(r.id), 'strength');
    perform public.week_target_for(r.id, public.local_week_start(r.id), 'nutrition');
    perform public.close_weeks(r.id);
    perform public.evaluate_achievements(r.id);
    n := n + 1;
  end loop;
  return n;
end $$;

-- ===== 0009_nutrition_diary.sql =====
-- Phase 2a, diary: nutrition targets, food diary and saved foods.

-- Tables ----------------------------------------------------------------------------------------

create table public.nutrition_targets (
  user_id    uuid not null references auth.users on delete cascade default auth.uid(),
  valid_from date not null,
  kcal       integer not null check (kcal between 1000 and 6000),
  protein_g  integer not null check (protein_g between 20 and 400),
  carbs_g    integer not null check (carbs_g between 0 and 900),
  fat_g      integer not null check (fat_g between 20 and 300),
  mode       text not null check (mode in ('auto', 'manual')),
  created_at timestamptz not null default now(),
  primary key (user_id, valid_from)
);

create table public.food_logs (
  id         uuid primary key,
  user_id    uuid not null references auth.users on delete cascade default auth.uid(),
  day        date not null,
  meal       text not null check (meal in ('breakfast', 'lunch', 'dinner', 'snack')),
  name       text not null check (char_length(name) between 1 and 120),
  brand      text check (char_length(brand) <= 80),
  source     text not null check (source in ('taco', 'off', 'custom', 'quick', 'import')),
  source_id  text check (char_length(source_id) <= 64),
  grams      numeric(6,1) check (grams > 0 and grams <= 5000),
  kcal       numeric(6,1) not null check (kcal between 0 and 5000),
  protein_g  numeric(5,1) not null default 0 check (protein_g between 0 and 500),
  carbs_g    numeric(5,1) not null default 0 check (carbs_g between 0 and 500),
  fat_g      numeric(5,1) not null default 0 check (fat_g between 0 and 500),
  fiber_g    numeric(5,1) check (fiber_g between 0 and 200),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index food_logs_user_day on public.food_logs (user_id, day);

create table public.user_foods (
  id            uuid primary key,
  user_id       uuid not null references auth.users on delete cascade default auth.uid(),
  source        text not null check (source in ('taco', 'off', 'custom')),
  source_id     text check (char_length(source_id) <= 64),
  barcode       text check (barcode ~ '^[0-9]{8,14}$'),
  favorite      boolean not null default false,
  name          text not null check (char_length(name) between 1 and 120),
  brand         text check (char_length(brand) <= 80),
  kcal_100g     numeric(6,1) not null check (kcal_100g between 0 and 900),
  protein_100g  numeric(5,1) not null default 0 check (protein_100g between 0 and 100),
  carbs_100g    numeric(5,1) not null default 0 check (carbs_100g between 0 and 100),
  fat_100g      numeric(5,1) not null default 0 check (fat_100g between 0 and 100),
  serving_g     numeric(6,1) check (serving_g > 0 and serving_g <= 2000),
  serving_label text check (char_length(serving_label) <= 40),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index user_foods_barcode on public.user_foods (user_id, barcode) where barcode is not null;

-- Today in the signed-in person's time zone. RLS policies and the invoker triggers run as the
-- client and need it; local_today(uuid) itself stays closed so nobody can probe another person.
create function public.my_local_today() returns date
language sql stable security definer set search_path = public as $$
  select public.local_today(auth.uid())
$$;
revoke all on function public.my_local_today() from public, anon;
grant execute on function public.my_local_today() to authenticated;

-- Access ----------------------------------------------------------------------------------------

alter table public.nutrition_targets enable row level security;
alter table public.food_logs enable row level security;
alter table public.user_foods enable row level security;

revoke all on public.nutrition_targets, public.food_logs, public.user_foods from anon;
revoke truncate on public.nutrition_targets, public.food_logs, public.user_foods from authenticated;
revoke delete on public.nutrition_targets from authenticated;

create policy nutrition_targets_select_own on public.nutrition_targets
  for select to authenticated using (user_id = auth.uid());
create policy nutrition_targets_insert_own on public.nutrition_targets
  for insert to authenticated with check (
    user_id = auth.uid()
    and (valid_from > public.my_local_today()
         or (valid_from = public.my_local_today()
             and not exists (select 1 from public.nutrition_targets t where t.user_id = auth.uid()))));
create policy nutrition_targets_update_own on public.nutrition_targets
  for update to authenticated
  using (user_id = auth.uid() and valid_from > public.my_local_today())
  with check (user_id = auth.uid() and valid_from > public.my_local_today());

create policy food_logs_select_own on public.food_logs
  for select to authenticated using (user_id = auth.uid());
create policy food_logs_insert_own on public.food_logs
  for insert to authenticated with check (user_id = auth.uid());
create policy food_logs_update_own on public.food_logs
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy food_logs_delete_own on public.food_logs
  for delete to authenticated using (user_id = auth.uid());

create policy user_foods_select_own on public.user_foods
  for select to authenticated using (user_id = auth.uid());
create policy user_foods_insert_own on public.user_foods
  for insert to authenticated with check (user_id = auth.uid());
create policy user_foods_update_own on public.user_foods
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy user_foods_delete_own on public.user_foods
  for delete to authenticated using (user_id = auth.uid());

-- Guards ----------------------------------------------------------------------------------------
-- Security invoker: the rules apply only to client roles. Security definer functions and the
-- cascade from auth.users run as the owner and pass untouched.

create function public.food_logs_guard() returns trigger
language plpgsql security invoker set search_path = public as $$
declare
  v_today date;
begin
  if current_user not in ('authenticated', 'anon') then
    return coalesce(new, old);
  end if;

  v_today := public.my_local_today();
  if (tg_op <> 'DELETE' and new.day not in (v_today - 1, v_today))
     or (tg_op <> 'INSERT' and old.day not in (v_today - 1, v_today)) then
    raise exception 'day_closed' using errcode = 'P0001';
  end if;

  if tg_op = 'DELETE' then return old; end if;

  if new.source = 'import' then
    raise exception 'import_forbidden' using errcode = 'P0001';
  end if;

  if tg_op = 'UPDATE' and (new.user_id <> old.user_id or new.day <> old.day) then
    raise exception 'item_immutable' using errcode = 'P0001';
  end if;

  if tg_op = 'INSERT' and (
      select count(*) from public.food_logs
       where user_id = new.user_id and day = new.day and id <> new.id) >= 200 then
    raise exception 'too_many_items' using errcode = 'P0001';
  end if;

  new.updated_at := least(new.updated_at, now());
  if tg_op = 'UPDATE' and new.updated_at < old.updated_at then
    return null;
  end if;
  return new;
end $$;

create trigger food_logs_guard before insert or update or delete on public.food_logs
  for each row execute function public.food_logs_guard();

create function public.user_foods_guard() returns trigger
language plpgsql security invoker set search_path = public as $$
begin
  if current_user not in ('authenticated', 'anon') then
    return new;
  end if;
  if tg_op = 'INSERT' and (
      select count(*) from public.user_foods where user_id = new.user_id and id <> new.id) >= 500 then
    raise exception 'too_many_foods' using errcode = 'P0001';
  end if;
  return new;
end $$;

create trigger user_foods_guard before insert on public.user_foods
  for each row execute function public.user_foods_guard();

-- The target in force on a day: the row with the greatest valid_from <= day.
create function public.target_on(p_user uuid, p_day date) returns public.nutrition_targets
language sql stable security definer set search_path = public as $$
  select t from public.nutrition_targets t
   where t.user_id = p_user and t.valid_from <= p_day
   order by t.valid_from desc limit 1
$$;

revoke all on function public.food_logs_guard(), public.user_foods_guard(),
  public.target_on(uuid, date) from public, anon, authenticated;

-- ===== 0010_nutrition_close.sql =====
-- Phase 2a, day closing: day D closes at the start of D+2 local (spec 4.2), its summary goes to
-- nutrition_days and the server-only events it earns pay nutrition XP through award_xp (spec 6.3).

-- Closed days ---------------------------------------------------------------------------------

create table public.nutrition_days (
  user_id    uuid not null references auth.users on delete cascade,
  day        date not null,
  kcal       numeric(9,1) not null,          -- 200 items x 5000 kcal fit
  protein_g  numeric(9,1) not null,
  carbs_g    numeric(9,1) not null,
  fat_g      numeric(9,1) not null,
  meals      smallint not null,              -- meals with at least one item
  target     jsonb,                          -- the target in force; null on an imported day without one
  logged     boolean not null,
  on_target  boolean not null,
  balanced   boolean not null,
  imported   boolean not null default false, -- 2b; never pays XP nor counts in metrics
  closed_at  timestamptz not null default now(),
  primary key (user_id, day)
);

alter table public.nutrition_days enable row level security;
create policy nutrition_days_select_own on public.nutrition_days
  for select to authenticated using (user_id = auth.uid());
revoke insert, update, delete, truncate on public.nutrition_days from anon, authenticated;
revoke select on public.nutrition_days from anon;

-- Classification (spec 6.2) -------------------------------------------------------------------
-- Exact numeric arithmetic, so 90% and 110% of the target count and nothing past them does.

create function public.classify_nutrition_day(
  p_kcal numeric, p_protein numeric, p_carbs numeric, p_fat numeric, p_meals int, p_target jsonb
) returns jsonb
language plpgsql immutable security definer set search_path = public as $$
declare
  v_kcal    numeric := (p_target ->> 'kcal')::numeric;
  v_protein numeric := (p_target ->> 'protein_g')::numeric;
  v_carbs   numeric := (p_target ->> 'carbs_g')::numeric;
  v_fat     numeric := (p_target ->> 'fat_g')::numeric;
  v_logged  boolean;
  v_on      boolean;
  v_bal     boolean;
begin
  v_logged := coalesce(p_meals >= 2 and p_kcal >= v_kcal * 0.5, false);
  v_on := v_logged and coalesce(abs(p_kcal - v_kcal) <= v_kcal * 0.1 and p_protein >= v_protein, false);
  v_bal := v_on and coalesce(abs(p_carbs - v_carbs) <= v_carbs * 0.2
                             and abs(p_fat - v_fat) <= v_fat * 0.2, false);
  return jsonb_build_object('logged', v_logged, 'on_target', v_on, 'balanced', v_bal);
end $$;

-- Closing -------------------------------------------------------------------------------------
-- Every pending day from the first period up to local_today - 2. Days outside a period or without
-- a target in force are not judged and get no row. Runs as the owner: the server-only events pass
-- RLS and the 14-day window, and award_xp pays them.

create function public.close_nutrition_days(p_user uuid) returns integer
language plpgsql security definer set search_path = public as $$
declare
  v_first  date;
  v_last   date;
  v_day    date;
  v_t      public.nutrition_targets;
  v_target jsonb;
  v_kcal   numeric;
  v_prot   numeric;
  v_carbs  numeric;
  v_fat    numeric;
  v_meals  integer;
  v_class  jsonb;
  v_ref    text;
  n        integer := 0;
begin
  perform pg_advisory_xact_lock(hashtextextended('xp:' || p_user::text, 0));
  select min(started_on) into v_first from public.nutrition_periods where user_id = p_user;
  if v_first is null then return 0; end if;
  v_last := public.local_today(p_user) - 2;

  for v_day in
    select d::date from generate_series(v_first, v_last, interval '1 day') d
     where not exists (select 1 from public.nutrition_days x where x.user_id = p_user and x.day = d::date)
     order by 1
  loop
    continue when not public.nutrition_active_on(p_user, v_day);
    select * into v_t from public.target_on(p_user, v_day);
    continue when v_t.valid_from is null;
    v_target := jsonb_build_object('kcal', v_t.kcal, 'protein_g', v_t.protein_g,
                                   'carbs_g', v_t.carbs_g, 'fat_g', v_t.fat_g);

    select coalesce(sum(kcal), 0), coalesce(sum(protein_g), 0), coalesce(sum(carbs_g), 0),
           coalesce(sum(fat_g), 0), count(distinct meal)
      into v_kcal, v_prot, v_carbs, v_fat, v_meals
      from public.food_logs where user_id = p_user and day = v_day;
    v_class := public.classify_nutrition_day(v_kcal, v_prot, v_carbs, v_fat, v_meals, v_target);

    insert into public.nutrition_days
      (user_id, day, kcal, protein_g, carbs_g, fat_g, meals, target, logged, on_target, balanced)
    values (p_user, v_day, v_kcal, v_prot, v_carbs, v_fat, v_meals, v_target,
            (v_class ->> 'logged')::boolean, (v_class ->> 'on_target')::boolean,
            (v_class ->> 'balanced')::boolean);

    v_ref := 'nutrition:' || to_char(v_day, 'YYYY-MM-DD');
    if (v_class ->> 'logged')::boolean then
      insert into public.activity_events (user_id, pillar, kind, occurred_on, source_ref)
      values (p_user, 'nutrition', 'day_logged', v_day, v_ref) on conflict do nothing;
    end if;
    if (v_class ->> 'on_target')::boolean then
      insert into public.activity_events (user_id, pillar, kind, occurred_on, source_ref)
      values (p_user, 'nutrition', 'day_on_target', v_day, v_ref) on conflict do nothing;
    end if;
    if (v_class ->> 'balanced')::boolean then
      insert into public.activity_events (user_id, pillar, kind, occurred_on, source_ref)
      values (p_user, 'nutrition', 'macros_balanced', v_day, v_ref) on conflict do nothing;
    end if;
    n := n + 1;
  end loop;
  return n;
end $$;

revoke all on function public.classify_nutrition_day(numeric, numeric, numeric, numeric, int, jsonb),
  public.close_nutrition_days(uuid) from public, anon, authenticated;

-- XP per event: the nutrition branch (spec 6.3) ---------------------------------------------------
-- Copied from 0008_weekly_targets_pillar.sql; the strength branch is unchanged. Nutrition has its
-- own reasons so nothing of strength (training_week, week_targets, weeks_on_target, target_hit)
-- ever counts them.

create or replace function public.award_xp() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  v_week   date := public.week_start_of(new.occurred_on);
  v_target smallint;
  v_count  integer;
begin
  -- One award at a time per user: the counts below decide the amount.
  perform pg_advisory_xact_lock(hashtextextended('xp:' || new.user_id::text, 0));

  if new.pillar = 'nutrition' then
    if new.kind = 'day_on_target' then
      v_target := public.week_target_for(new.user_id, v_week, 'nutrition');
      select count(*) into v_count from public.xp_ledger
       where user_id = new.user_id and week_start = v_week and reason = 'nutrition_day';
      if v_count < v_target then
        insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
        values (new.user_id, 'nutrition', public.session_xp(v_target, v_count + 1), 'nutrition_day', new.id, v_week);
        if v_count + 1 = v_target then
          insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
          values (new.user_id, 'nutrition', 150, 'nutrition_week_target', new.id, v_week);
        end if;
      else
        select count(*) into v_count from public.xp_ledger
         where user_id = new.user_id and week_start = v_week and reason = 'nutrition_day_extra';
        if v_count < 2 then
          insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
          values (new.user_id, 'nutrition', 25, 'nutrition_day_extra', new.id, v_week);
        end if;
      end if;
    elsif new.kind = 'macros_balanced' then
      select count(*) into v_count from public.xp_ledger
       where user_id = new.user_id and week_start = v_week and reason = 'nutrition_balanced';
      if v_count < 3 then
        insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
        values (new.user_id, 'nutrition', 30, 'nutrition_balanced', new.id, v_week);
      end if;
    elsif new.kind = 'day_logged' then
      if not exists (
        select 1 from public.xp_ledger l join public.activity_events e on e.id = l.event_id
         where l.user_id = new.user_id and l.reason = 'nutrition_logged' and e.occurred_on = new.occurred_on
      ) then
        insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
        values (new.user_id, 'nutrition', 10, 'nutrition_logged', new.id, v_week);
      end if;
    end if;
    perform public.evaluate_achievements(new.user_id);
    return null;
  end if;

  if new.pillar <> 'strength' then return null; end if;

  if new.kind = 'workout_completed' then
    v_target := public.week_target_for(new.user_id, v_week, 'strength');
    select count(*) into v_count from public.xp_ledger
     where user_id = new.user_id and week_start = v_week and reason = 'workout';
    if v_count < v_target then
      insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
      values (new.user_id, 'strength', public.session_xp(v_target, v_count + 1), 'workout', new.id, v_week);
      if v_count + 1 = v_target then
        insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
        values (new.user_id, 'strength', 150, 'week_target', new.id, v_week);
        -- A goal met in a week already judged (a session logged into the past) changes that
        -- week's verdict: replay the streak from the start.
        if exists (select 1 from public.streaks
                    where user_id = new.user_id and kind = 'training_week' and last_period >= v_week) then
          perform public.close_weeks(new.user_id, true);
        end if;
      end if;
    else
      select count(*) into v_count from public.xp_ledger
       where user_id = new.user_id and week_start = v_week and reason = 'workout_extra';
      if v_count < 2 then
        insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
        values (new.user_id, 'strength', 25, 'workout_extra', new.id, v_week);
      end if;
    end if;
  elsif new.kind = 'pr' then
    select count(*) into v_count from public.xp_ledger
     where user_id = new.user_id and week_start = v_week and reason = 'pr';
    if v_count < 3 then
      insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
      values (new.user_id, 'strength', 30, 'pr', new.id, v_week);
    end if;
  elsif new.kind = 'weight_logged' then
    if not exists (
      select 1 from public.xp_ledger l join public.activity_events e on e.id = l.event_id
       where l.user_id = new.user_id and l.reason = 'weight' and e.occurred_on = new.occurred_on
    ) then
      insert into public.xp_ledger (user_id, pillar, amount, reason, event_id, week_start)
      values (new.user_id, 'strength', 10, 'weight', new.id, v_week);
    end if;
  end if;
  perform public.evaluate_achievements(new.user_id);
  return null;
end $$;

-- ===== 0011_nutrition_week.sql =====
-- Phase 2a, the nutrition week: the nutrition_week streak (spec 4.3, 6.4) with shields and neutral
-- weeks (spec 3.4), the private nutrition badges and their metrics, the day history RPC and the
-- daily safety net that 0013 schedules.

-- Weekly streak ---------------------------------------------------------------------------------
-- Its own function: close_weeks (strength) does not change. A week is judged once its seven days
-- have closed (week_start + 6 <= local_today - 2) and closed days never reopen, so a verdict is
-- final and nothing is ever replayed.
--   goal met                        -> +1 (and a shield every 4, at most 2)
--   a day outside a period, missed  -> neutral: nothing changes (the activation week included)
--   missed with a streak and shield -> the shield goes, the streak stays
--   otherwise                       -> 0

create function public.close_nutrition_weeks(p_user uuid) returns void
language plpgsql security definer set search_path = public as $$
declare
  v_last   date;
  v_s      public.streaks%rowtype;
  v_week   date;
  v_judged integer := 0;
begin
  perform pg_advisory_xact_lock(hashtextextended('xp:' || p_user::text, 0));
  -- The last week whose seven days have all closed.
  v_last := public.local_today(p_user) - 8;
  insert into public.streaks (user_id, kind) values (p_user, 'nutrition_week') on conflict do nothing;
  select * into v_s from public.streaks where user_id = p_user and kind = 'nutrition_week' for update;

  if v_s.last_period is null then
    select public.week_start_of(min(started_on)) into v_week
      from public.nutrition_periods where user_id = p_user;
  else
    v_week := v_s.last_period + 7;
  end if;

  while v_week is not null and v_week <= v_last loop
    if exists (select 1 from public.xp_ledger
                where user_id = p_user and reason = 'nutrition_week_target' and week_start = v_week) then
      v_s.current := v_s.current + 1;
      v_s.best := greatest(v_s.best, v_s.current);
      if v_s.current % 4 = 0 then v_s.shields := least(2, v_s.shields + 1); end if;
    elsif exists (select 1 from generate_series(v_week, v_week + 6, interval '1 day') d
                   where not public.nutrition_active_on(p_user, d::date)) then
      null;   -- neutral week
    elsif v_s.current > 0 and v_s.shields > 0 then
      v_s.shields := v_s.shields - 1;
    else
      v_s.current := 0;
    end if;
    v_s.last_period := v_week;
    v_week := v_week + 7;
    v_judged := v_judged + 1;
  end loop;

  if v_judged > 0 then
    update public.streaks
       set current = v_s.current, best = v_s.best, shields = v_s.shields, last_period = v_s.last_period
     where user_id = p_user and kind = 'nutrition_week';
    -- Streak badges for people who only meet the cron.
    perform public.evaluate_achievements(p_user);
  end if;
end $$;

revoke all on function public.close_nutrition_weeks(uuid) from public, anon, authenticated;

-- Closing days ----------------------------------------------------------------------------------
-- Same as 0010 with two changes: the scan starts the day after the last closed day (a day skipped
-- once, outside a period or without a target, can never become judgeable later, so it is safe and
-- keeps every call short), and the weeks are judged at the end.

create or replace function public.close_nutrition_days(p_user uuid) returns integer
language plpgsql security definer set search_path = public as $$
declare
  v_first  date;
  v_last   date;
  v_day    date;
  v_t      public.nutrition_targets;
  v_target jsonb;
  v_kcal   numeric;
  v_prot   numeric;
  v_carbs  numeric;
  v_fat    numeric;
  v_meals  integer;
  v_class  jsonb;
  v_ref    text;
  n        integer := 0;
begin
  perform pg_advisory_xact_lock(hashtextextended('xp:' || p_user::text, 0));
  select min(started_on) into v_first from public.nutrition_periods where user_id = p_user;
  if v_first is null then return 0; end if;
  -- Imported days (2b) are history and do not mark how far closing went.
  select greatest(v_first, max(day) + 1) into v_first
    from public.nutrition_days where user_id = p_user and not imported;
  v_last := public.local_today(p_user) - 2;

  for v_day in
    select d::date from generate_series(v_first, v_last, interval '1 day') d
     where not exists (select 1 from public.nutrition_days x where x.user_id = p_user and x.day = d::date)
     order by 1
  loop
    continue when not public.nutrition_active_on(p_user, v_day);
    select * into v_t from public.target_on(p_user, v_day);
    continue when v_t.valid_from is null;
    v_target := jsonb_build_object('kcal', v_t.kcal, 'protein_g', v_t.protein_g,
                                   'carbs_g', v_t.carbs_g, 'fat_g', v_t.fat_g);

    select coalesce(sum(kcal), 0), coalesce(sum(protein_g), 0), coalesce(sum(carbs_g), 0),
           coalesce(sum(fat_g), 0), count(distinct meal)
      into v_kcal, v_prot, v_carbs, v_fat, v_meals
      from public.food_logs where user_id = p_user and day = v_day;
    v_class := public.classify_nutrition_day(v_kcal, v_prot, v_carbs, v_fat, v_meals, v_target);

    insert into public.nutrition_days
      (user_id, day, kcal, protein_g, carbs_g, fat_g, meals, target, logged, on_target, balanced)
    values (p_user, v_day, v_kcal, v_prot, v_carbs, v_fat, v_meals, v_target,
            (v_class ->> 'logged')::boolean, (v_class ->> 'on_target')::boolean,
            (v_class ->> 'balanced')::boolean);

    v_ref := 'nutrition:' || to_char(v_day, 'YYYY-MM-DD');
    if (v_class ->> 'logged')::boolean then
      insert into public.activity_events (user_id, pillar, kind, occurred_on, source_ref)
      values (p_user, 'nutrition', 'day_logged', v_day, v_ref) on conflict do nothing;
    end if;
    if (v_class ->> 'on_target')::boolean then
      insert into public.activity_events (user_id, pillar, kind, occurred_on, source_ref)
      values (p_user, 'nutrition', 'day_on_target', v_day, v_ref) on conflict do nothing;
    end if;
    if (v_class ->> 'balanced')::boolean then
      insert into public.activity_events (user_id, pillar, kind, occurred_on, source_ref)
      values (p_user, 'nutrition', 'macros_balanced', v_day, v_ref) on conflict do nothing;
    end if;
    n := n + 1;
  end loop;

  perform public.close_nutrition_weeks(p_user);
  return n;
end $$;

revoke all on function public.close_nutrition_days(uuid) from public, anon, authenticated;

-- Daily safety net (0013 schedules it) ------------------------------------------------------------
-- Everyone with an open period, or with a closed period whose last week is not judged yet (its
-- days may still be pending too). Returns how many people it went through.

create function public.close_all_nutrition_days() returns integer
language plpgsql security definer set search_path = public as $$
declare
  r record;
  n integer := 0;
begin
  for r in
    select distinct p.user_id from public.nutrition_periods p
      left join public.streaks s on s.user_id = p.user_id and s.kind = 'nutrition_week'
     where p.ended_on is null or p.ended_on >= coalesce(s.last_period + 7, p.started_on)
  loop
    perform public.close_nutrition_days(r.user_id);
    n := n + 1;
  end loop;
  return n;
end $$;

revoke all on function public.close_all_nutrition_days() from public, anon, authenticated;

-- Badges ------------------------------------------------------------------------------------------
-- Private badges are never shown to friends (progress_card leaves them out from 0012 on).
-- Mirrored by src/features/gamification/achievements.ts (gamification-catalog.test.ts).

alter table public.achievement_catalog add column private boolean not null default false;
alter table public.achievement_catalog drop constraint achievement_catalog_metric_check;
alter table public.achievement_catalog add constraint achievement_catalog_metric_check check (metric in (
  'workouts', 'prs', 'week_targets', 'best_streak', 'weigh_in_run', 'level', 'early_workouts', 'friends',
  'challenges_won', 'nutrition_logged_days', 'nutrition_on_target_days', 'nutrition_week_targets',
  'nutrition_best_streak', 'protein_best_run'));

insert into public.achievement_catalog (code, metric, threshold, xp, sort, private) values
  ('nutrition_first_day',     'nutrition_logged_days',      1,   50, 300, true),
  ('nutrition_days_10',       'nutrition_on_target_days',  10,  100, 310, true),
  ('nutrition_days_50',       'nutrition_on_target_days',  50,  200, 320, true),
  ('nutrition_days_100',      'nutrition_on_target_days', 100,  300, 330, true),
  ('nutrition_days_250',      'nutrition_on_target_days', 250,  500, 340, true),
  ('nutrition_week_target_1', 'nutrition_week_targets',     1,   75, 350, true),
  ('nutrition_streak_4',      'nutrition_best_streak',      4,  150, 360, true),
  ('nutrition_streak_12',     'nutrition_best_streak',     12,  400, 370, true),
  ('nutrition_streak_26',     'nutrition_best_streak',     26,  800, 380, true),
  ('protein_7',               'protein_best_run',           7,  100, 390, true);

-- Achievement metrics: 0004's, plus the nutrition ones. Imported days (2b) never count.

create or replace function public.achievement_stats(p_user uuid) returns jsonb
language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'workouts', (select count(*) from public.activity_events where user_id = p_user and kind = 'workout_completed'),
    'prs', (select count(*) from public.activity_events where user_id = p_user and kind = 'pr'),
    'week_targets', (select count(*) from public.xp_ledger where user_id = p_user and reason = 'week_target'),
    'best_streak', coalesce((select best from public.streaks where user_id = p_user and kind = 'training_week'), 0),
    -- Longest run of consecutive weigh-in days (gaps and islands).
    'weigh_in_run', coalesce((
      select max(n) from (
        select count(*) as n from (
          select d - (row_number() over (order by d))::int as grp
            from (select distinct occurred_on as d from public.activity_events
                   where user_id = p_user and kind = 'weight_logged') days
        ) runs group by grp
      ) lengths), 0),
    -- Live sessions only: the app sends the local start hour for those, never for backfills.
    'early_workouts', (select count(*) from public.activity_events
                        where user_id = p_user and kind = 'workout_completed'
                          and jsonb_typeof(payload -> 'hour') = 'number' and (payload ->> 'hour')::numeric < 7),
    'friends', (select count(*) from public.friendships where p_user in (user_a, user_b)),
    'challenges_won', (select count(*) from public.challenge_members where user_id = p_user and won),
    'nutrition_logged_days', (select count(*) from public.nutrition_days
                               where user_id = p_user and not imported and logged),
    'nutrition_on_target_days', (select count(*) from public.nutrition_days
                                  where user_id = p_user and not imported and on_target),
    'nutrition_week_targets', (select count(*) from public.xp_ledger
                                where user_id = p_user and reason = 'nutrition_week_target'),
    'nutrition_best_streak', coalesce((select best from public.streaks
                                        where user_id = p_user and kind = 'nutrition_week'), 0),
    -- Longest run of consecutive closed days with protein at or above the target in force.
    'protein_best_run', coalesce((
      select max(n) from (
        select count(*) as n from (
          select day - (row_number() over (order by day))::int as grp
            from public.nutrition_days
           where user_id = p_user and not imported
             and protein_g >= (target ->> 'protein_g')::numeric
        ) runs group by grp
      ) lengths), 0)
  )
$$;

revoke all on function public.achievement_stats(uuid) from public, anon, authenticated;

-- Day history -------------------------------------------------------------------------------------
-- The closed days of a range (at most 62 days) and the target in force today. Closes the pending
-- days first, so it is volatile.

create function public.get_nutrition_days(p_from date, p_to date) returns jsonb
language plpgsql volatile security definer set search_path = public as $$
declare
  v_uid uuid := auth.uid();
  v_t   public.nutrition_targets;
begin
  if v_uid is null then raise exception 'not_signed_in' using errcode = '28000'; end if;
  if not exists (select 1 from public.profiles where id = v_uid) then
    raise exception 'no_profile' using errcode = 'P0002';
  end if;
  if p_from is null or p_to is null or p_to < p_from or p_to - p_from + 1 > 62 then
    raise exception 'invalid_range' using errcode = '22023';
  end if;
  perform public.close_nutrition_days(v_uid);
  select * into v_t from public.target_on(v_uid, public.local_today(v_uid));
  return jsonb_build_object(
    'target', case when v_t.valid_from is null then null else jsonb_build_object(
      'valid_from', v_t.valid_from, 'mode', v_t.mode, 'kcal', v_t.kcal, 'protein_g', v_t.protein_g,
      'carbs_g', v_t.carbs_g, 'fat_g', v_t.fat_g) end,
    'days', coalesce((
      select jsonb_agg(jsonb_build_object(
               'day', d.day, 'kcal', d.kcal, 'protein_g', d.protein_g, 'carbs_g', d.carbs_g,
               'fat_g', d.fat_g, 'meals', d.meals, 'target', d.target, 'logged', d.logged,
               'on_target', d.on_target, 'balanced', d.balanced, 'imported', d.imported) order by d.day)
        from public.nutrition_days d
       where d.user_id = v_uid and d.day between p_from and p_to), '[]'::jsonb));
end $$;

revoke all on function public.get_nutrition_days(date, date) from public, anon;
grant execute on function public.get_nutrition_days(date, date) to authenticated;

-- ===== 0012_nutrition_progress.sql =====
-- Phase 2a, progress: the public card learns about pillars (spec 6.5), the owner gets the
-- nutrition block, the pillar radar (spec 8.4) and the full badge list, and friends get none of
-- those. Bodies copied from 0008_weekly_targets_pillar.sql; signatures do not change.

-- Whether a week touched a nutrition period. A period turned on and off the same day
-- (ended_on = started_on - 1) covers no day and touches nothing.
create function public.nutrition_week_active(p_user uuid, p_week date) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.nutrition_periods
     where user_id = p_user and started_on <= p_week + 6
       and (ended_on is null or (ended_on >= p_week and ended_on >= started_on)))
$$;

revoke all on function public.nutrition_week_active(uuid, date) from public, anon, authenticated;

-- Public card -----------------------------------------------------------------------------------
-- What friends see (get_friends) and the base of the owner's answer. Stable: it only reads, so the
-- strength target falls back to the profile when the week was not frozen yet.
--   week.max     960 per pillar active in the week (strength always, nutrition when a period
--                touched the week)
--   week.pillars the week's XP by pillar; bonus is the general XP (pillar null: badges, challenges)
--   achievements without the private ones

create or replace function public.progress_card(p_user uuid) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  v_week   date := public.local_week_start(p_user);
  v_total  bigint := public.total_xp(p_user);
  v_target smallint;
  v_streak public.streaks%rowtype;
  v_count  jsonb;
  v_split  jsonb;
begin
  v_target := coalesce(
    (select target from public.weekly_targets where user_id = p_user and pillar = 'strength' and week_start = v_week),
    (select days_per_week from public.profiles where id = p_user), 3);
  select * into v_streak from public.streaks where user_id = p_user and kind = 'training_week';
  select jsonb_build_object(
           'workouts', count(*) filter (where reason = 'workout'),
           'extras', count(*) filter (where reason = 'workout_extra'),
           'prs', count(*) filter (where reason = 'pr'),
           'target_hit', count(*) filter (where reason = 'week_target') > 0),
         jsonb_build_object(
           'strength', coalesce(sum(amount) filter (where pillar = 'strength'), 0),
           'nutrition', coalesce(sum(amount) filter (where pillar = 'nutrition'), 0),
           'bonus', coalesce(sum(amount) filter (where pillar is null), 0))
    into v_count, v_split
    from public.xp_ledger where user_id = p_user and week_start = v_week;
  return jsonb_build_object(
    'total_xp', v_total,
    'level', public.level_json(v_total),
    'pillars', (
      select coalesce(jsonb_object_agg(p.name, public.level_json(p.xp) || jsonb_build_object('xp', p.xp)), '{}'::jsonb)
        from (select e::text as name,
                     coalesce((select sum(amount) from public.xp_ledger where user_id = p_user and pillar = e), 0)::bigint as xp
                from unnest(enum_range(null::public.pillar)) e) p
       where p.name = 'strength' or p.xp > 0),
    'week', jsonb_build_object(
              'start', v_week, 'xp', public.week_xp(p_user, v_week),
              'max', 960 * (1 + public.nutrition_week_active(p_user, v_week)::int),
              'target', v_target, 'pillars', v_split) || v_count,
    'streak', jsonb_build_object('current', coalesce(v_streak.current, 0), 'best', coalesce(v_streak.best, 0),
                                 'shields', coalesce(v_streak.shields, 0)),
    'achievements', coalesce((
      select jsonb_agg(jsonb_build_object('code', u.code, 'unlocked_at', u.unlocked_at) order by u.unlocked_at, u.code)
        from public.user_achievements u join public.achievement_catalog c on c.code = u.code
       where u.user_id = p_user and not c.private), '[]'::jsonb)
  );
end $$;

revoke all on function public.progress_card(uuid) from public, anon, authenticated;

-- Pillar radar (spec 8.4) -----------------------------------------------------------------------
-- Consistency of a pillar over 4 closed weeks: its XP / (960 x active weeks), at most 1. p_offset
-- 0 is the last 4 closed weeks, 1 the 4 before them. Null without an active week in the window.
--   strength  closed: every week before the running one; active: from the first week close_weeks
--             judges (the creation week, or an earlier event's)
--   nutrition closed: week_start + 6 <= local_today - 2; active: the week touched a period,
--             counted whole
-- General bonuses (pillar null) never count.

create function public.pillar_consistency(p_user uuid, p_pillar public.pillar, p_offset int) returns numeric
language plpgsql stable security definer set search_path = public as $$
declare
  v_last  date;
  v_first date;
  v_weeks date[];
  v_xp    bigint;
begin
  if p_pillar = 'strength' then
    v_last := public.local_week_start(p_user) - 7;
    select least(
      (select public.week_start_of(min(occurred_on)) from public.activity_events where user_id = p_user),
      (select public.week_start_of((created_at at time zone coalesce(timezone, 'America/Sao_Paulo'))::date)
         from public.profiles where id = p_user)
    ) into v_first;
  elsif p_pillar = 'nutrition' then
    v_last := public.week_start_of(public.local_today(p_user) - 8);
  else
    return null;
  end if;
  v_last := v_last - 28 * p_offset;

  select array_agg(w::date) into v_weeks
    from generate_series(v_last - 21, v_last, interval '7 days') w
   where case when p_pillar = 'strength' then w::date >= v_first
              else public.nutrition_week_active(p_user, w::date) end;
  if v_weeks is null then return null; end if;

  select coalesce(sum(amount), 0) into v_xp from public.xp_ledger
   where user_id = p_user and pillar = p_pillar and week_start = any(v_weeks);
  return least(1, round(v_xp::numeric / (960 * cardinality(v_weeks)), 4));
end $$;

revoke all on function public.pillar_consistency(uuid, public.pillar, int) from public, anon, authenticated;

-- The owner's extras ----------------------------------------------------------------------------
-- Joined by get_my_progress, never sent to friends: every badge (private included), the nutrition
-- block (only once the pillar was ever turned on) and the radar.
--   nutrition.target       T of the running week (frozen or, failing that, the profile's)
--   nutrition.on_target    closed days of the running week on target; logged likewise
--   nutrition.confirms_on  the day today closes (today + 2)
--   nutrition.last_closed  the last closed day and the XP its events paid
--   nutrition.last_week    the last week with its seven days closed, from the first period's week

create function public.my_progress_extras(p_user uuid) returns jsonb
language plpgsql stable security definer set search_path = public as $$
declare
  v_today  date := public.local_today(p_user);
  v_week   date := public.week_start_of(v_today);
  v_lw     date := public.week_start_of(v_today - 8);
  v_first  date;
  v_streak public.streaks%rowtype;
  v_day    public.nutrition_days%rowtype;
  v_nut    jsonb;
begin
  select public.week_start_of(min(started_on)) into v_first
    from public.nutrition_periods where user_id = p_user;
  if v_first is not null then
    select * into v_streak from public.streaks where user_id = p_user and kind = 'nutrition_week';
    select * into v_day from public.nutrition_days
     where user_id = p_user and not imported order by day desc limit 1;
    v_nut := jsonb_build_object(
      'target', coalesce(
        (select target from public.weekly_targets where user_id = p_user and pillar = 'nutrition' and week_start = v_week),
        (select nutrition_days_per_week from public.profiles where id = p_user), 5),
      'on_target', (select count(*) from public.nutrition_days
                     where user_id = p_user and not imported and on_target and day between v_week and v_week + 6),
      'logged', (select count(*) from public.nutrition_days
                  where user_id = p_user and not imported and logged and day between v_week and v_week + 6),
      'streak', jsonb_build_object('current', coalesce(v_streak.current, 0), 'best', coalesce(v_streak.best, 0),
                                   'shields', coalesce(v_streak.shields, 0)),
      'confirms_on', v_today + 2,
      'last_closed', case when v_day.day is null then null else jsonb_build_object(
        'day', v_day.day, 'logged', v_day.logged, 'on_target', v_day.on_target, 'balanced', v_day.balanced,
        'xp', coalesce((
          select sum(l.amount) from public.xp_ledger l join public.activity_events e on e.id = l.event_id
           where l.user_id = p_user and e.user_id = p_user and e.pillar = 'nutrition'
             and e.occurred_on = v_day.day), 0)) end,
      'last_week', case when v_lw < v_first then null else jsonb_build_object(
        'start', v_lw,
        'target_hit', exists (select 1 from public.xp_ledger
                               where user_id = p_user and reason = 'nutrition_week_target' and week_start = v_lw)) end);
  end if;

  return jsonb_build_object(
    'achievements', coalesce((
      select jsonb_agg(jsonb_build_object('code', code, 'unlocked_at', unlocked_at) order by unlocked_at, code)
        from public.user_achievements where user_id = p_user), '[]'::jsonb),
    'radar', jsonb_build_object(
      'strength', jsonb_build_object('current', public.pillar_consistency(p_user, 'strength', 0),
                                     'previous', public.pillar_consistency(p_user, 'strength', 1)),
      'nutrition', jsonb_build_object('current', public.pillar_consistency(p_user, 'nutrition', 0),
                                      'previous', public.pillar_consistency(p_user, 'nutrition', 1))))
    || case when v_nut is null then '{}'::jsonb else jsonb_build_object('nutrition', v_nut) end;
end $$;

revoke all on function public.my_progress_extras(uuid) from public, anon, authenticated;

-- The owner's answer ----------------------------------------------------------------------------
-- Freezes both pillars' targets, closes strength weeks and pending nutrition days (which judges
-- the nutrition weeks too), then joins the card and the extras; the extras' badge list replaces
-- the card's.

create or replace function public.get_my_progress() returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_uid   uuid := auth.uid();
  v_today date;
  v_card  jsonb;
begin
  if v_uid is null then raise exception 'not_signed_in' using errcode = '28000'; end if;
  if not exists (select 1 from public.profiles where id = v_uid) then
    raise exception 'no_profile' using errcode = 'P0002';
  end if;
  perform pg_advisory_xact_lock(hashtextextended('xp:' || v_uid::text, 0));
  v_today := public.local_today(v_uid);
  perform public.week_target_for(v_uid, public.week_start_of(v_today), 'strength');
  perform public.week_target_for(v_uid, public.week_start_of(v_today), 'nutrition');
  perform public.close_weeks(v_uid);
  perform public.close_nutrition_days(v_uid);
  perform public.evaluate_achievements(v_uid);
  v_card := public.progress_card(v_uid);
  return v_card || public.my_progress_extras(v_uid) || jsonb_build_object(
    'today', v_today,
    'stats', public.achievement_stats(v_uid) || jsonb_build_object('level', (v_card -> 'level' ->> 'level')::int),
    'week', (v_card -> 'week') || jsonb_build_object('weighed_today', exists (
      select 1 from public.xp_ledger l join public.activity_events e on e.id = l.event_id
       where l.user_id = v_uid and l.reason = 'weight' and e.occurred_on = v_today)));
end $$;

revoke all on function public.get_my_progress() from public, anon;
grant execute on function public.get_my_progress() to authenticated;

-- ===== 0013_nutrition_cron.sql =====
-- Phase 2a: daily safety net for nutrition. get_my_progress and get_nutrition_days already close
-- pending days and weeks whenever the app opens; this pays the days, the weekly streak and the
-- badges of people who stay away. It only does something where pg_cron exists (Supabase, once the
-- extension is enabled; see docs/SETUP.md §7). Elsewhere, the PGlite tests included, it is a no-op.
do $$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron with schema pg_catalog;
    -- Same job name again updates the schedule instead of adding a second job.
    execute $cron$ select cron.schedule('close-nutrition-days', '30 6 * * *', 'select public.close_all_nutrition_days()') $cron$;
  end if;
exception when others then
  raise notice 'close-nutrition-days not scheduled: %', sqlerrm;
end $$;

-- ===== 0014_food_measures.sql =====
-- Phase 2b, personal food measures ("concha" = 120 g of a given food).

create table public.food_measures (
  id         uuid primary key,
  user_id    uuid not null references auth.users on delete cascade default auth.uid(),
  food_key   text not null check (food_key ~ '^(taco|off|custom):[A-Za-z0-9-]{1,64}$'),
  label      text not null check (char_length(btrim(label)) between 1 and 30),
  grams      numeric(6,1) not null check (grams >= 1 and grams <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index food_measures_user_food on public.food_measures (user_id, food_key);

alter table public.food_measures enable row level security;

revoke all on public.food_measures from anon;
revoke truncate on public.food_measures from authenticated;

create policy food_measures_select_own on public.food_measures
  for select to authenticated using (user_id = auth.uid());
create policy food_measures_insert_own on public.food_measures
  for insert to authenticated with check (user_id = auth.uid());
create policy food_measures_update_own on public.food_measures
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy food_measures_delete_own on public.food_measures
  for delete to authenticated using (user_id = auth.uid());

-- Security invoker: limits apply to client roles only; the cascade from auth.users and security
-- definer functions run as the owner and pass untouched. Counts skip the incoming id so an upsert
-- of an existing measure on a full set still passes.
create function public.food_measures_guard() returns trigger
language plpgsql security invoker set search_path = public as $$
begin
  if current_user not in ('authenticated', 'anon') then
    return coalesce(new, old);
  end if;

  if tg_op = 'INSERT' then
    if (select count(*) from public.food_measures
         where user_id = new.user_id and food_key = new.food_key and id <> new.id) >= 10
       or (select count(*) from public.food_measures
            where user_id = new.user_id and id <> new.id) >= 500 then
      raise exception 'too_many_measures' using errcode = 'P0001';
    end if;
  end if;

  -- A measure never moves to another food or person: the per-food limit is only counted on insert.
  if tg_op = 'UPDATE' and (new.user_id <> old.user_id or new.food_key <> old.food_key) then
    raise exception 'item_immutable' using errcode = 'P0001';
  end if;

  new.updated_at := least(new.updated_at, now());
  if tg_op = 'UPDATE' and new.updated_at < old.updated_at then
    return null;
  end if;
  return new;
end $$;

create trigger food_measures_guard before insert or update on public.food_measures
  for each row execute function public.food_measures_guard();

revoke all on function public.food_measures_guard() from public, anon, authenticated;

-- ===== 0015_nutrition_challenge.sql =====
-- Phase 2b, nutrition challenge: nutrition_days_on_target counts the closed days each participant
-- spent on target in the period (spec 5 and 6.2). Team adds them up, solo needs each person to
-- reach the goal. Creating or joining asks for the pillar on and for the opt-in that shows the
-- other participants that count (and nothing else). A day closes at the start of D+2, so these
-- challenges close when the challenge's own today is past ends_on + 2, after the participants'
-- pending days are closed.
--
-- The functions below are the latest bodies (0004, 0006) with only the nutrition parts added.
-- create_challenge and join_challenge gain p_share_nutrition (last, default false): the old
-- signatures are dropped and the grants made again.

-- Tables -------------------------------------------------------------------------------------------

alter table public.challenges drop constraint challenges_template_check;
alter table public.challenges add constraint challenges_template_check
  check (template in ('workouts_count', 'weeks_on_target', 'volume_total', 'nutrition_days_on_target'));

alter table public.challenge_members add column share_nutrition boolean not null default false;

-- Progress -----------------------------------------------------------------------------------------
-- nutrition_days_on_target: closed days on target, not imported, inside the period and inside one
-- of the person's pillar periods.

create or replace function public.challenge_progress(p_challenge uuid, p_user uuid) returns numeric
language plpgsql stable security definer set search_path = public as $$
declare
  c public.challenges%rowtype;
  v numeric;
begin
  select * into c from public.challenges where id = p_challenge;
  if not found then return null; end if;
  if c.template = 'workouts_count' then
    select count(*) into v from public.activity_events
     where user_id = p_user and kind = 'workout_completed' and occurred_on between c.starts_on and c.ends_on;
  elsif c.template = 'weeks_on_target' then
    select count(*) into v from public.xp_ledger
     where user_id = p_user and reason = 'week_target'
       and week_start between public.week_start_of(c.starts_on) and c.ends_on;
  elsif c.template = 'nutrition_days_on_target' then
    select count(*) into v from public.nutrition_days
     where user_id = p_user and on_target and not imported and day between c.starts_on and c.ends_on
       and public.nutrition_active_on(p_user, day);
  else
    select coalesce(sum(least(greatest((payload ->> 'vol')::numeric, 0), 100000)), 0) into v
      from public.activity_events
     where user_id = p_user and kind = 'workout_completed' and occurred_on between c.starts_on and c.ends_on
       and jsonb_typeof(payload -> 'vol') = 'number';
    v := round(v * (case when (select unit from public.profiles where id = p_user) = 'lb'
                         then 0.45359237 else 1 end) / 1000, 1);
  end if;
  return v;
end $$;

-- Creating and joining -----------------------------------------------------------------------------

drop function public.create_challenge(text, text, text, numeric, date, date, uuid[], boolean);

create function public.create_challenge(
  p_template text, p_title text, p_mode text, p_target numeric, p_starts_on date, p_ends_on date,
  p_invitees uuid[], p_share_volume boolean default false, p_share_nutrition boolean default false
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  v_me     uuid := auth.uid();
  v_title  text := btrim(coalesce(p_title, ''));
  v_today  date;
  v_people uuid[];
  v_id     uuid;
begin
  if v_me is null then raise exception 'not_signed_in' using errcode = '28000'; end if;
  if not exists (select 1 from public.profiles where id = v_me) then
    raise exception 'no_profile' using errcode = 'P0002';
  end if;
  v_today := public.local_today(v_me);
  select coalesce(array_agg(distinct u), '{}') into v_people
    from unnest(coalesce(p_invitees, '{}'::uuid[])) u where u is not null and u <> v_me;

  -- Same rules as checkChallenge in src/features/social/templates.ts.
  if p_template is null
     or p_template not in ('workouts_count', 'weeks_on_target', 'volume_total', 'nutrition_days_on_target')
     or p_mode is null or p_mode not in ('team', 'solo')
     or (p_template = 'weeks_on_target' and p_mode <> 'solo')
     or char_length(v_title) not between 1 and 60
     or p_starts_on is null or p_ends_on is null
     or p_ends_on - p_starts_on not between 6 and 91
     or p_starts_on < v_today or p_starts_on > v_today + 30
     or p_target is null or p_target <> trunc(p_target) or p_target < 1
     or (p_template = 'workouts_count' and p_target > 500)
     or (p_template = 'volume_total' and p_target > 5000)
     or (p_template = 'weeks_on_target'
         and p_target > (public.week_start_of(p_ends_on) - public.week_start_of(p_starts_on)) / 7 + 1)
     or (p_template = 'nutrition_days_on_target'
         and p_target > (p_ends_on - p_starts_on + 1)
                        * (case when p_mode = 'team' then 1 + cardinality(v_people) else 1 end))
     or cardinality(v_people) not between 1 and 19 then
    raise exception 'invalid_challenge' using errcode = 'P0001';
  end if;
  if exists (select 1 from unnest(v_people) u where not public.are_friends(v_me, u)) then
    raise exception 'not_friends' using errcode = 'P0001';
  end if;
  if p_template = 'volume_total' and not coalesce(p_share_volume, false) then
    raise exception 'volume_opt_in_required' using errcode = 'P0001';
  end if;
  if p_template = 'nutrition_days_on_target' then
    if not (select nutrition_enabled from public.profiles where id = v_me) then
      raise exception 'nutrition_off' using errcode = 'P0001';
    end if;
    if not coalesce(p_share_nutrition, false) then
      raise exception 'nutrition_opt_in_required' using errcode = 'P0001';
    end if;
  end if;
  perform pg_advisory_xact_lock(hashtextextended('challenge-create:' || v_me::text, 0));
  if (select count(*) from public.challenges where created_by = v_me and status = 'active') >= 10 then
    raise exception 'challenge_limit' using errcode = 'P0001';
  end if;

  insert into public.challenges (template, title, mode, target, starts_on, ends_on, created_by)
  values (p_template, v_title, p_mode, p_target, p_starts_on, p_ends_on, v_me)
  returning id into v_id;
  insert into public.challenge_members (challenge_id, user_id, invited_by, joined_at, share_volume, share_nutrition)
  values (v_id, v_me, null, public.app_now(), p_template = 'volume_total', p_template = 'nutrition_days_on_target');
  insert into public.challenge_members (challenge_id, user_id, invited_by)
  select v_id, u, v_me from unnest(v_people) u;
  return jsonb_build_object('id', v_id);
end $$;

drop function public.join_challenge(uuid, boolean);

create function public.join_challenge(
  p_id uuid, p_share_volume boolean default false, p_share_nutrition boolean default false
) returns void
language plpgsql security definer set search_path = public as $$
declare
  v_me uuid := auth.uid();
  v_c  public.challenges%rowtype;
  v_m  public.challenge_members%rowtype;
begin
  if v_me is null then raise exception 'not_signed_in' using errcode = '28000'; end if;
  select * into v_m from public.challenge_members where challenge_id = p_id and user_id = v_me for update;
  if not found then raise exception 'challenge_not_found' using errcode = 'P0002'; end if;
  select * into v_c from public.challenges where id = p_id;
  if v_c.status <> 'active' or public.challenge_today(v_c.created_by, v_c.timezone) > v_c.ends_on then
    raise exception 'challenge_closed' using errcode = 'P0001';
  end if;
  if v_m.joined_at is not null then return; end if;
  if v_c.template = 'volume_total' and not coalesce(p_share_volume, false) then
    raise exception 'volume_opt_in_required' using errcode = 'P0001';
  end if;
  if v_c.template = 'nutrition_days_on_target' then
    if not coalesce((select nutrition_enabled from public.profiles where id = v_me), false) then
      raise exception 'nutrition_off' using errcode = 'P0001';
    end if;
    if not coalesce(p_share_nutrition, false) then
      raise exception 'nutrition_opt_in_required' using errcode = 'P0001';
    end if;
  end if;
  update public.challenge_members
     set joined_at = public.app_now(), share_volume = (v_c.template = 'volume_total'),
         share_nutrition = (v_c.template = 'nutrition_days_on_target')
   where challenge_id = p_id and user_id = v_me;
end $$;

revoke all on function
  public.create_challenge(text, text, text, numeric, date, date, uuid[], boolean, boolean),
  public.join_challenge(uuid, boolean, boolean)
  from public, anon;
grant execute on function
  public.create_challenge(text, text, text, numeric, date, date, uuid[], boolean, boolean),
  public.join_challenge(uuid, boolean, boolean)
  to authenticated;

-- Closing ------------------------------------------------------------------------------------------
-- How many days past ends_on a challenge waits before it closes: the last two days of a nutrition
-- challenge are judged only at the start of D+2.

create or replace function public.challenge_grace(p_template text) returns integer
language sql immutable security definer set search_path = public as $$
  select case when p_template = 'nutrition_days_on_target' then 2 else 0 end
$$;
revoke all on function public.challenge_grace(text) from public, anon, authenticated;

-- As 0006, with the grace above and, for nutrition, every participant's pending days closed after
-- their XP locks are taken (close_nutrition_days takes the same lock again) and before final.
create or replace function public.close_challenge(p_challenge uuid) returns boolean
language plpgsql security definer set search_path = public as $$
declare
  c         public.challenges%rowtype;
  v_members uuid[];
  v_won     boolean;
  v_user    uuid;
  r         record;
begin
  perform pg_advisory_xact_lock(hashtextextended('challenge-close', 0));
  select * into c from public.challenges where id = p_challenge for update;
  if not found or c.status <> 'active'
     or public.challenge_today(c.created_by, c.timezone) <= c.ends_on + public.challenge_grace(c.template) then
    return false;
  end if;
  delete from public.challenge_members where challenge_id = p_challenge and joined_at is null;
  select coalesce(array_agg(user_id order by user_id), '{}') into v_members
    from public.challenge_members where challenge_id = p_challenge;
  if cardinality(v_members) < 2 then
    update public.challenges set status = 'cancelled', closed_at = public.app_now() where id = p_challenge;
    return true;
  end if;
  perform public.lock_users(v_members);
  if c.template = 'nutrition_days_on_target' then
    foreach v_user in array v_members loop
      perform public.close_nutrition_days(v_user);
    end loop;
  end if;
  update public.challenge_members
     set final = coalesce(public.challenge_progress(p_challenge, user_id), 0)
   where challenge_id = p_challenge;
  if c.mode = 'team' then
    select sum(final) >= c.target into v_won from public.challenge_members where challenge_id = p_challenge;
    update public.challenge_members set won = v_won where challenge_id = p_challenge;
  else
    update public.challenge_members set won = (final >= c.target) where challenge_id = p_challenge;
    select bool_or(won) into v_won from public.challenge_members where challenge_id = p_challenge;
  end if;
  update public.challenges
     set status = case when v_won then 'won' else 'lost' end, closed_at = public.app_now()
   where id = p_challenge;
  for r in select user_id from public.challenge_members
            where challenge_id = p_challenge and won order by user_id loop
    perform public.award_bonus_xp(r.user_id, 300, 'challenge:' || p_challenge::text);
    perform public.evaluate_achievements(r.user_id);
  end loop;
  return true;
end $$;

create or replace function public.close_due_challenges(p_user uuid) returns integer
language plpgsql security definer set search_path = public as $$
declare
  r record;
  n integer := 0;
begin
  for r in
    select c.id from public.challenges c
      join public.challenge_members m on m.challenge_id = c.id and m.user_id = p_user
     where c.status = 'active'
       and c.ends_on + public.challenge_grace(c.template) < public.challenge_today(c.created_by, c.timezone)
     order by c.id
  loop
    if public.close_challenge(r.id) then n := n + 1; end if;
  end loop;
  return n;
end $$;

create or replace function public.close_all_challenges() returns integer
language plpgsql security definer set search_path = public as $$
declare
  r record;
  n integer := 0;
begin
  for r in select id from public.challenges
            where status = 'active'
              and ends_on + public.challenge_grace(template) < public.challenge_today(created_by, timezone)
            order by id loop
    if public.close_challenge(r.id) then n := n + 1; end if;
  end loop;
  return n;
end $$;

-- ===== 0016_nutrition_history.sql =====
-- Phase 2b, history calendar: get_nutrition_days (0011) also returns the XP each day earned and the
-- weekly goal of every week the range touches. Same signature, same privileges, same 62-day limit.
--
--   xp     per day: the nutrition ledger rows paid for that day's events (source_ref
--          'nutrition:<day>'), the +150 of the day that met the weekly goal included. Bonuses
--          without an event (achievements, challenges) belong to no day and are left out.
--   weeks  per Monday-start week touched by [p_from, p_to], whole weeks even when the range cuts
--          them: start, target (the value frozen for that week; failing that the next frozen one,
--          as week_target_for reads it, then the profile's), on_target (closed days on target in
--          the week) and target_hit (the weekly goal bonus was paid for it).
-- Reads only: unlike week_target_for it never freezes a week.

create or replace function public.get_nutrition_days(p_from date, p_to date) returns jsonb
language plpgsql volatile security definer set search_path = public as $$
declare
  v_uid uuid := auth.uid();
  v_t   public.nutrition_targets;
begin
  if v_uid is null then raise exception 'not_signed_in' using errcode = '28000'; end if;
  if not exists (select 1 from public.profiles where id = v_uid) then
    raise exception 'no_profile' using errcode = 'P0002';
  end if;
  if p_from is null or p_to is null or p_to < p_from or p_to - p_from + 1 > 62 then
    raise exception 'invalid_range' using errcode = '22023';
  end if;
  perform public.close_nutrition_days(v_uid);
  select * into v_t from public.target_on(v_uid, public.local_today(v_uid));
  return jsonb_build_object(
    'target', case when v_t.valid_from is null then null else jsonb_build_object(
      'valid_from', v_t.valid_from, 'mode', v_t.mode, 'kcal', v_t.kcal, 'protein_g', v_t.protein_g,
      'carbs_g', v_t.carbs_g, 'fat_g', v_t.fat_g) end,
    'days', coalesce((
      select jsonb_agg(jsonb_build_object(
               'day', d.day, 'kcal', d.kcal, 'protein_g', d.protein_g, 'carbs_g', d.carbs_g,
               'fat_g', d.fat_g, 'meals', d.meals, 'target', d.target, 'logged', d.logged,
               'on_target', d.on_target, 'balanced', d.balanced, 'imported', d.imported,
               'xp', coalesce((
                 select sum(l.amount)::int
                   from public.activity_events e
                   join public.xp_ledger l on l.event_id = e.id
                  where e.user_id = v_uid and e.pillar = 'nutrition'
                    and e.source_ref = 'nutrition:' || to_char(d.day, 'YYYY-MM-DD')
                    and l.user_id = v_uid and l.pillar = 'nutrition'), 0)) order by d.day)
        from public.nutrition_days d
       where d.user_id = v_uid and d.day between p_from and p_to), '[]'::jsonb),
    'weeks', (
      select jsonb_agg(jsonb_build_object(
               'start', w.start,
               'target', coalesce(
                 (select t.target from public.weekly_targets t
                   where t.user_id = v_uid and t.pillar = 'nutrition' and t.week_start >= w.start
                   order by t.week_start limit 1),
                 (select p.nutrition_days_per_week from public.profiles p where p.id = v_uid), 5),
               'on_target', (select count(*)::int from public.nutrition_days d
                              where d.user_id = v_uid and d.on_target and not d.imported
                                and d.day between w.start and w.start + 6),
               'target_hit', exists (select 1 from public.xp_ledger l
                                      where l.user_id = v_uid and l.reason = 'nutrition_week_target'
                                        and l.week_start = w.start)) order by w.start)
        from (select g::date as start
                from generate_series(public.week_start_of(p_from), public.week_start_of(p_to),
                                     interval '7 days') g) w));
end $$;

revoke all on function public.get_nutrition_days(date, date) from public, anon;
grant execute on function public.get_nutrition_days(date, date) to authenticated;
